= HOLE Not-For-Profit Licence Agreement
(Please read carefully. You may want to print a copy for reference)

FOREWORD
SmartSci Limited is pleased to make the production version of its software available free of charge to Not-For-Profit users (as defined below). 

== HOLE END USER LICENCE AGREEMENT NOT-FOR-PROFIT VERSION

=== GRANT.
SmartSci Limited ("SmartSci") hereby grants you a non-exclusive licence to use its accompanying software product HOLE (the "Software") free of charge if and only if 
you are a student, faculty member or staff member of an educational institution, or an employee of a charitable non-profit organisation, engaged in 
non-proprietary scientific projects, i.e. projects all results of which will be made public without preferential prior disclosure to a for-profit organisation.

Government agencies are not necessarily considered charitable non-profit organisations for the purposes of this licence agreement.

If you do not fit within the description above, you 
should not use the not-for-profit version and you should instead apply for a commercial licence. 
If you are using the Software free of charge, you will not be entitled to support or telephone assistance.

You may not:

* permit other individuals to use the Software except under the terms listed below;
* modify, translate, reverse engineer, decompile, disassemble (except to the extent applicable laws specifically prohibit such restriction), or create derivative works based on the Software;
* copy the Software (except for back-up purposes);
* rent, lease, transfer, or otherwise transfer rights to, the Software;
* remove any proprietary notices or labels on the Software. 


=== SOFTWARE.
This licence does not grant you any right to any enhancement or update.

=== TITLE.
Title, ownership rights, and intellectual property rights in and to the Software shall remain in SmartSci and/or its suppliers. The Software is protected by the copyright laws of the United Kingdom, the United States and under international copyright treaties. Title, ownership rights, and intellectual property rights in and to the content accessed through the Software is the property of the applicable content owner and may be protected by applicable copyright or other law. This licence gives you no rights to such content.

=== CITATION.
You agree to acknowledge the use of the Software in all publications or reports of results obtained using the Software and to cite the following reference:

Smart, O.S., Goodfellow, J.M., Wallace, B.A. (1993).  The pore dimensions of gramicidin A.  _Biophys. J._, *65*, 2455-2460. http://dx.doi.org/10.1016%2FS0006-3495(93)81293-1


=== DISCLAIMER OF WARRANTY.
Since the Software is provided free of charge, the Software is provided on an "AS IS" basis, without warranty of any kind, including without limitation the warranties of merchant-ability, fitness for a particular purpose and non-infringement. The entire risk as to the quality and performance of the Software is borne by you. Should the Software prove defective, you and not SmartSci assume the entire cost of any service and repair. In addition, the security mechanisms implemented by the Software have inherent limitations, and you must determine that the Software sufficiently meets your requirements. This disclaimer of warranty constitutes an essential part of the agreement.

=== LIMITATION OF LIABILITY.
UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, TORT, CONTRACT, OR OTHERWISE, SHALL SmartSci OR ITS SUPPLIERS OR RE-SELLERS BE LIABLE TO YOU OR ANY OTHER PERSON FOR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES. IN NO EVENT WILL SmartSci BE LIABLE FOR ANY DAMAGES IN EXCESS OF THE AMOUNT PAID FOR THIS LICENCE TO THE SOFTWARE, EVEN IF SmartSci SHALL HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES, OR FOR ANY CLAIM BY ANY OTHER PARTY. THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIABILITY FOR DEATH OR PERSONAL INJURY TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. FURTHERMORE, SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION AND EXCLUSION MAY NOT APPLY TO YOU.

=== TERMINATION.
There is no time limitation to this licence, provided you comply with the conditions stated above. This licence will terminate automatically if you fail to comply with any of those conditions, and on such termination you must destroy all copies of the Software.

=== MISCELLANEOUS.
This Agreement represents the complete agreement concerning this licence between the parties and supersedes all prior agreements and representations between them. It may be amended only by a writing executed by both parties. If any provision of this Agreement is held to be unenforceable for any reason, such provision shall be reformed only to the extent necessary to make it enforceable. This Agreement shall be governed by and construed under British law as such law applies to agreements between United Kingdom residents entered into and to be performed within Britain. 
